apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdemo
  labels:
    app: springdemo
spec:
  selector:
    matchLabels:
      app: springdemo
  template:
    metadata:
      labels:
        app: springdemo
    spec:
      containers:
      - image: __IMAGE__@__DIGEST__
        imagePullPolicy: Always
        name: springdemo
        ports:
          - name: http-server
            containerPort: 8080
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        args: ["--spring.application.json=$(BINDING)"]
        env:
        - name: BINDING
          valueFrom:
            secretKeyRef:
              name: binding-wrm-demo-db
              key: binding
        volumeMounts:
          # name must match the volume name below
          - name: secret-volume
            mountPath: /.postgresql/
            readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: cert-secret
---
apiVersion: v1
kind: Service
metadata:
  name: springdemo
  labels:
    app: springdemo
spec:
  ports:
    - port: 8080
      targetPort: http-server
  selector:
    app: springdemo
  type: NodePort
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: springdemo
  labels:
    app: springdemo
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: springdemo
    weight: 100
